[package]
name = "explore-component"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ui-frame = { path = "../../ui-frame" }
diff-component = { path = "../diff" }
files-component = { path = "../files" }
review-explore = { path = "../../review-explore" }
review-explore-page-opening = { path = "../../review-explore-page-opening" }
review-explore-page-settings = { path = "../../review-explore-page-settings" }
review-source = { path = "../../review-source" }
component-core = { path = "../../component-core" }
ui-actions = { path = "../../ui-actions" }
ui-controls = { path = "../../ui-controls" }
ui-panes = { path = "../../ui-panes" }
ui-events = { path = "../../ui-events" }
ui-theme = { path = "../../ui-theme" }
ui-qr-code = { path = "../../ui-qr-code" }
ui-shortcuts = { path = "../../ui-shortcuts" }
comment-editor = { path = "../../comment-editor" }
markdown-rendering = { path = "../../markdown-rendering" }
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }


[dev-dependencies]
review-repository = { path = "../../review-repository" }
review-types = { path = "../../review-types" }
serde_json.workspace = true

[lints]
workspace = true
