[package]
name = "review-explore-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
markdown-marks = { path = "../markdown-marks" }
mermaid-js = { path = "../mermaid-js" }
review-explore = { path = "../review-explore" }
review-explore-round-settings = { path = "../review-explore-round-settings" }
review-repository = { path = "../review-repository" }
review-source = { path = "../review-source" }
review-types = { path = "../review-types" }

[dev-dependencies]
schemars.workspace = true
serde_json.workspace = true

[lints]
workspace = true
