[package]
name = "review-explore-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
review-explore = { path = "../review-explore" }
review-repository = { path = "../review-repository" }
review-source = { path = "../review-source" }

[dev-dependencies]
schemars.workspace = true
serde_json.workspace = true

[lints]
workspace = true
