[package]
name = "markdown-rendering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ratatui.workspace = true
ratatui-legacy.workspace = true
ratatui-markdown.workspace = true
syntax-highlighting = { path = "../syntax-highlighting" }
ui-theme = { path = "../ui-theme" }

[lints]
workspace = true
