[package]
name = "pr-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crossterm.workspace = true
eyre.workspace = true
pr-core = { path = "../pr-core" }
pr-state = { path = "../pr-state" }
ratatui = { workspace = true, features = ["crossterm"] }
signal-hook.workspace = true
serde_json.workspace = true

[dev-dependencies]
pr-tests = { path = "../pr-tests" }
tempfile.workspace = true

[lints]
workspace = true
