[package]
name = "review-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eyre.workspace = true
ratatui = { workspace = true, features = ["crossterm"] }
ratatui-markdown.workspace = true
review-lsp = { path = "../review-lsp" }
review-repository = { path = "../review-repository" }
review-state = { path = "../review-state" }
review-store = { path = "../review-store" }
syntect.workspace = true
toasts = { path = "../toasts" }
toml.workspace = true
two-face.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
